#!/bin/bash

if [ -n "$GGH_IGNORE_GITLEAKS" ]; then
    echo "ggh-gitleaks: ignoring due to override"
    exit 0
fi

if ! command -v gitleaks 2>&1 >/dev/null
then
    echo "gitleaks not installed, skipping" >&2
    exit 0
fi

gitleaks git --pre-commit --redact --staged --verbose
