# Copyright (C) 2025-2026 bryce thuilot <bryce@thuilot.io>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

name: release

on:
  release:
    types: ["created"]

env:
  OCAML_COMPILER: 5
  SUFFIX: ${{ github.event.release.prerelease && '-prerelease' || '' }}
  RELEASE_NAME: ${{ github.event.release.name }}


permissions:
  contents: read

jobs:
  publish-docker:
    name: publish docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: set commit sha
        id: commitsha
        run: echo "short=$(git rev-parse --short=10 HEAD)" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # ratchet:docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup qemu
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # ratchet:docker/setup-qemu-action@v4.0.0
      - name: setup buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # ratchet:docker/setup-buildx-action@v4.0.0
      - name: docker build
        id: docker-build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # ratchet:docker/build-push-action@v7.1.0
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          build-args: |
            GGHCOMMITSHA=${{ steps.commitsha.outputs.short }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ggh:${{ env.RELEASE_NAME }}${{ env.SUFFIX }}
            ghcr.io/${{ github.repository_owner }}/ggh:latest${{ env.SUFFIX }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-binary:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            arch: amd64
          - os: ubuntu-24.04-arm
            name: linux
            arch: arm64
          - os: macos-latest
            name: darwin
            arch: arm64
            # TODO(bryce): find a way to build
            # darwin amd64 without paying money
            # - os: macos-latest-large
            #   name: darwin
            #   arch: amd64
            # TODO(bryce): build for windows
            # - os: windows-latest
            #   name: windows
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: set-up ocaml
        uses: ocaml/setup-ocaml@e32b06a3e831ff2fbc6f08cf35be2085e3918014 # ratchet:ocaml/setup-ocaml@v3.6.1
        with:
          ocaml-compiler: ${{ env.OCAML_COMPILER }}

      - run: opam install . --deps-only

      - run: opam exec -- dune build

      - run: |
          export FILE_NAME="ggh-${TAG_NAME}-${OS_NAME}-${OS_ARCH}.tar.gz"
          cp _build/default/bin/main.exe ggh
          tar -zcvf ${FILE_NAME} ggh
          if [[ "$OS_NAME" == "darwin" ]]; then
            shasum  --algorithm 256 ${FILE_NAME} | awk '{print $1}' > ${FILE_NAME}.sha256
          else
            sha256sum ./$FILE_NAME > ${FILE_NAME}.sha256
          fi
          gh release upload $TAG_NAME ./${FILE_NAME}.sha256
          gh release upload $TAG_NAME ./$FILE_NAME
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          OS_NAME: ${{ matrix.name }}
          GH_TOKEN: ${{ github.token }}
          OS_ARCH: ${{ matrix.arch }}
